const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#D4AF37",
    background: "#0A192F",
    foreground: "#FFFFFF",
    card: "#0B1C3D",
    cardForeground: "#FFFFFF",
    primary: "#D4AF37",
    primaryForeground: "#0A192F",
    secondary: "#12264A",
    secondaryForeground: "#FFFFFF",
    muted: "#12264A",
    mutedForeground: "#8A9BB5",
    accent: "#E5C158",
    accentForeground: "#0A192F",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    warningBackground: "#fffbeb",
    warningBorder: "#fcd34d",
    warningForeground: "#b45309",
    warningMutedForeground: "#92400e",
    border: "#1E3563",
    input: "#1E3563",
    splashBg: "#0A192F",
    gold: "#D4AF37",
    goldLight: "#E5C158",
    goldDark: "#A0823A",
    navy: "#0A192F",
    navyMid: "#0B1C3D",
    navyLight: "#12264A",
    // Bright luxury canvas (white surfaces with navy cards)
    canvas: "#FFFFFF",
    canvasAlt: "#F4F6FA",
    textOnLight: "#0A192F",
    mutedOnLight: "#5A6B85",
    borderOnLight: "#E3E8F2",
    cyanLight: "#9BDCFF",
  },
  radius: 12,
};

export default colors;
