uploads = []
outputs = []

[[generated]]
id = "wzk4Bn-UYPk6cuIRo5W8X"
uri = "file://artifacts/dar-altamaiz-tours/assets/images/icon.png"
type = "image"
title = "dar-altamaiz-tours-icon"

[[generated]]
id = "Y8S3IdTe_k1PZ_wFE1sx3"
uri = "file://artifacts/dar-altamaiz-tours/assets/images/splash-bg.png"
type = "image"
title = "dar-altamaiz-tours-splash"
